Bug fix/ cw fixes
BeachCity/mastodon pull request #75
Opened 2019-06-04 16:13 UTC by joycem137

2019-06-04 18:44 UTC, aarchiba requested changes
There are a couple of things here I think might be bugs, and a design decision I want to question.

In fact, would a function "adjust_image_sensitivity(state)" be appropriate? instead of tracking deltas all over the place, you just call it whenever you think anything might have changed and if the image should be flagged sensitive it sets the flag. This is idempotent, and as long as it doesn't ever mark an image as not sensitive, it is harmless to throw it in anywhere anything might have changed - initialization, resetting, a change in CW state of any kind...

2019-06-04 18:44 UTC, aarchiba commented on app/javascript/mastodon/reducers/compose.js
> +  force_sensitive: false,
is it really a good idea to add another state variable rather than a method? the state of force_sensitive should always be "if CW button pressed or CW text nonempty", but if it's a variable there's a risk of it getting out of sync with that; why not just call a method that checks that condition every time you need it?

2019-06-04 18:44 UTC, aarchiba commented on app/javascript/mastodon/reducers/compose.js
> +        map.set('force_sensitive', true);
this *sets* force_sensitive when you turn off CWs, is that really okay?

2019-06-04 18:44 UTC, aarchiba commented on app/javascript/mastodon/reducers/compose.js
> +    map.set('sensitivity_change_disabled', false);
wait, what? is this a holdover of an old name for the setting?

2019-06-04 18:46 UTC, joycem137 commented on app/javascript/mastodon/reducers/compose.js
> +    map.set('sensitivity_change_disabled', false);
That is indeed a holdover.

2019-06-04 19:06 UTC, joycem137 commented on app/javascript/mastodon/reducers/compose.js
> +  force_sensitive: false,
I'm going to delete this and migrate to using a selector to compute this.

2019-06-04 19:14 UTC, joycem137 commented on app/javascript/mastodon/reducers/compose.js
> +        map.set('force_sensitive', true);
This sets force_sensitive when we click the CW button.  Specifically, this sets force_sensitive when we click the CW button while image sensititivy was false and we have some images attached.

2019-06-05 08:30 UTC, aarchiba reviewed
I think this should work fine, so in the interest of fixing things maybe it makes sense to put it in. I would like to suggest a little simplification, though, and some checks, but those could happen after we roll out the bug fix to our users.

Does case REDRAFT correctly set media sensitivity? I'm not clear how media are handled.

case COMPOSE_SPOILERNESS_CHANGE also contains a duplicate (specialized) version of the logic in isSpoilerActive.

We could actually replace isSpoilerActive(state) and a bunch of logic with enforceSpoilerSensitive(state, map) which checks whether state modified by map will have an active spoiler and if so sets sensitive in map. Then just call this everywhere you currently check isSpoilerActive.

2019-06-05 08:30 UTC, aarchiba commented on app/javascript/mastodon/reducers/compose.js
> +function isSpoilerActive(state) {
we often want to call this in the middle of an update operation, so can it take a second, optional argument `map`? So that it's checking "will spoilers be active when state is updated by map?" This would remove some of the duplication of logic below. In fact this isn't very useful as is because almost every time we want to use it it's because map is changing the activeness of the spoiler.

2019-06-05 08:30 UTC, aarchiba commented on app/javascript/mastodon/reducers/compose.js
> +      if (!isSpoilerActive(state)) {
I don't like that this stops you turning on sensitivity if the spoiler is active. That should never be an option but it's still peculiar logic. Why not split this in two:
```suggestion
      map.set('sensitive', !state.get('sensitive'));
      if (isSpoilerActive(state)) {
          map.set('sensitive', true);
      }
```
This way the logic is made explicit: this action flips the sensitivity. Except if the spoiler is active, tough luck, stays sensitive.

2019-06-05 08:30 UTC, aarchiba commented on app/javascript/mastodon/reducers/compose.js
> +      if (isSpoilerActive(state) || (enableAlwaysShowSpoiler && action.text.length > 0)) {
Here we're forced to duplicate the logic of isSpoilerActive because map might have changed state.

2019-06-05 08:30 UTC, aarchiba commented on app/javascript/mastodon/reducers/compose.js
> +        map.set('sensitive', true);
Here again we're duplicating the logic for isSpoilerActive because map might have changed state. I'd rather leave all mention of sensitive out and add our standard
```
if (isSpoilerActive(state,map)) {
    map.set('sensitive', true);
}
```

2019-06-05 08:30 UTC, aarchiba commented on app/javascript/mastodon/features/compose/containers/sensitive_button_container.js
> +  disabled: enableAlwaysShowSpoiler ? state.getIn(['compose', 'spoiler_text']).length > 0 : state.getIn(['compose', 'spoiler']),
I guess this logic duplication is kind of unavoidable in light of scoping limitations.

2019-06-05 08:30 UTC, aarchiba commented on app/javascript/mastodon/reducers/compose.js
> +    if (prevSize === 0 && (state.get('default_sensitive') || isSpoilerActive(state))) {
I'd rather simplify this logic:
```suggestion
    if (prevSize === 0 && state.get('default_sensitive')) {
        map.set('sensitive', true);
    }
    if (isSpoilerActive(state)) {
        map.set('sensitive', true);
    }
```
The idea is: write the obvious logic, then enforce the isSpoilerActive constraint.

2019-06-05 09:03 UTC, joycem137 commented on app/javascript/mastodon/reducers/compose.js
> +        map.set('sensitive', true);
I'm not sure if you can/should access data from map. You'd basically be checking for incoming data.

2019-06-05 09:04 UTC, joycem137 commented on app/javascript/mastodon/features/compose/containers/sensitive_button_container.js
> +  disabled: enableAlwaysShowSpoiler ? state.getIn(['compose', 'spoiler_text']).length > 0 : state.getIn(['compose', 'spoiler']),
Correct.  Plus, you can't access state in the same way here, since you have to specify the scope.

2019-06-05 09:06 UTC, joycem137 commented on app/javascript/mastodon/reducers/compose.js
> +function isSpoilerActive(state) {
I'd be inclined not to

2019-06-05 09:07 UTC, joycem137 commented on app/javascript/mastodon/reducers/compose.js
> +    if (prevSize === 0 && (state.get('default_sensitive') || isSpoilerActive(state))) {
That would change the behavior here.  We want to make sure we're changing states here.

2019-06-05 09:07 UTC, merged